Add API reference
maritaca-ai/maritalk-api pull request #145
Opened 2024-11-06 17:52 UTC by giovanaBonas

2024-11-06 18:00 UTC, rodrigo-f-nogueira approved these changes
Muito obrigado por adicionar isso tudo! Eu nao li com cautela, mas se tiver sugestões de edição de texto, eu faço em outra PR

2024-11-06 18:00 UTC, rodrigo-f-nogueira commented on documentation/api/pt/endpoints.md
> +# Maritaca API
Talvez chamar de "Test Maritaca Endpoint"?

2024-11-06 21:37 UTC, ZanezZephyrs requested changes

2024-11-06 21:37 UTC, ZanezZephyrs commented on documentation/api/pt/completion.md
> +- **Quando chat_mode=True**: espera-se uma lista de mensagens, cada uma com "role" (papel: system, user, assistant ou tool) e "content" (conteúdo da mensagem). Exemplo:
Isso ta errado, nossa rota legado "/inference" tinha esse parametro do chat_mode, essa nossa nova rota não tem. Então aqui sempre tem q ser a lista de mensagens.

O equivalente do "chat_mode"=False agr é usar o endpoint /api/completions.

2024-11-06 21:37 UTC, ZanezZephyrs commented on documentation/api/pt/completion.md
> +### logit_bias `object{str: float}` <sup class="sup-opcional">Opcional</sup>
n suportado atualmente

2024-11-06 21:38 UTC, ZanezZephyrs commented on documentation/api/pt/list-models.md
> +A lista de modelos fornece uma visão geral dos modelos disponíveis na API, incluindo informações básicas como proprietário e disponibilidade.
Não entendi mt bem, "informações básicas como proprietário e disponibilidade." que informação de proprietario?

2024-11-07 13:29 UTC, giovanaBonas commented on documentation/api/pt/endpoints.md
> +# Maritaca API
Seria uma boa mesmo, vou alterar

2024-11-07 13:29 UTC, giovanaBonas commented on documentation/api/pt/completion.md
> +- **Quando chat_mode=True**: espera-se uma lista de mensagens, cada uma com "role" (papel: system, user, assistant ou tool) e "content" (conteúdo da mensagem). Exemplo:
Valeu Thales, tem razão, vou alterar

2024-11-07 20:08 UTC, ZanezZephyrs approved these changes

2024-11-08 15:40 UTC, merged